# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-09 19:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oth', '0004_auto_20180128_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notif',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 2, 10, 1, 16, 18, 988892)),
        ),
    ]
