# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-20 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oth', '0008_auto_20181020_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='l_number',
            field=models.IntegerField(default=1),
        ),
    ]
