# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-06 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oth', '0008_auto_20180706_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total_level',
            name='totallevel',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
